CREATE DATABASE QUANLYGIAOVU
USE QUANLYGIAOVU

CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)
INSERT INTO KHOA VALUES
('KHMT', 'KHOA HOC MAY TINH', '2005-06-07', 'GV01'),
('HTTT', 'HE THONG THONG TIN', '2005-06-07', 'GV02'),
('CNPM', 'CONG NGHE PHAN MEM', '2005-06-07', 'GV04'),
('MTT', 'MANG VA TRUYEN THONG', '2005-10-20', 'GV03'),
('KTMT', 'KY THUAT MAY TINH', '2005-12-20', NULL);

CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)
INSERT INTO MONHOC VALUES 
('THDC', 'TIN HOC DAI CUONG', '4', '1', 'KHMT'),
('CTRR', 'CAU TRUC ROI RAC', '5', '0', 'KHMT'),
('CSDL', 'CO SO DU LIEU', '3', '1', 'HTTT'),
('CTDLGT', 'CAU TRUC DU LIEU VA GIAI THUAT', '3', '1', 'KHMT'),
('PTTKTT', 'PHAN TICH THIET KE THUAT TOAN', '3', '0','KHMT'),
('DHMT', 'DO HOA MAY TINH', '3', '1', 'KHMT'),
('KTMT', 'KIEN TRUC MAY TINH', '3', '0', 'KTMT'),
('TKCSDL', 'THIET KE CO SO DU LIEU', '3', '1', 'HTTT'),
('PTTKHTTT', 'PHAN TICH THIET KE HE THONG THONG TIN', '4', '1', 'HTTT'),
('HDH', 'HE DIEU HANH', '4', '0', 'KTMT'),
('NMCNPM', 'NHAP MON CONG NGHE PHAN MEM', '3', '0', 'CNPM'),
('LTCFW', 'LAP TRINH C FOR WIN', '3', '1', 'CNPM'),
('LTHDT', 'LAP TRINH HUONG DOI TUONG', '3' ,'1', 'CNPM');
ALTER TABLE MONHOC ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA);
ALTER TABLE MONHOC ADD CONSTRAINT CK_CHENHLECHTC CHECK (TCLT - TCTH <=3 AND TCLT - TCTH >= 0);

CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC)
)
INSERT INTO DIEUKIEN VALUES 
('CSDL', 'CTRR'),
('CSDL', 'CTDLGT'),
('CTDLGT', 'THDC'),
('PTTKTT', 'THDC'),
('PTTKTT', 'CTDLGT'),
('DHMT', 'THDC'),
('LTHDT', 'THDC'),
('PTTKHTTT', 'CSDL');
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH);
ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_MHTRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC (MAMH);


CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
)
INSERT INTO GIAOVIEN VALUES 
('GV01', 'HO THANH SON', 'PTS', 'GS', 'NAM', '1950-5-2', '2004-1-11', '5.00', '2250000', 'KHMT'),
('GV02', 'TRAN TAM THANH', 'TS', 'PGS', 'NAM', '1965-12-17', '2004-4-20', '4.50', '2025000', 'HTTT'),
('GV03', 'DO NGHIEM PHUNG', 'TS', 'GS', 'NU', '1950-8-1', '2004-9-23', '4.00', '1800000', 'CNPM'),
('GV04', 'TRAN NAM SON', 'TS', 'PGS', 'NAM', '1961-2-22', '2005-1-12', '4.50', '2025000', 'KTMT'),
('GV05', 'MAI THANH DANH', 'THS', 'GV', 'NAM', '1958-3-12', '2005-1-12', '3.00', '1350000', 'HTTT'),
('GV06', 'TRAN DOAN HUNG', 'TS', 'GV', 'NAM', '1953-3-11', '2005-1-12', '4.50', '2025000', 'KHMT'),
('GV07', 'NGUYEN MINH TIEN', 'THS', 'GV', 'NAM', '1971-11-23', '2005-3-1', '4.00', '1800000', 'KHMT'),
('GV08', 'LE THI TRAN', 'KS', NULL, 'NU', '1974-3-26', '2005-3-1', '1.69', '760500', 'KHMT'),
('GV09', 'NGUYEN TO LAN', 'THS', 'GV', 'NU', '1966-12-31', '2005-3-1', '4.00', '1800000', 'HTTT'),
('GV10', 'LE TRAN ANH LOAN', 'KS', NULL, 'NU', '1972-7-17', '2005-3-1', '1.86', '837000', 'CNPM'),
('GV11', 'HO THANH TUNG', 'CN', 'GV', 'NAM', '1980-1-12', '2005-5-15', '2.67', '1201500', 'MTT'),
('GV12', 'TRAN VAN ANH', 'CN', NULL, 'NU', '1981-3-29', '2005-5-15', '1.69', '760500', 'CNPM'),
('GV13', 'NGUYEN LINH DAN', 'CN', NULL, 'NU', '1980-5-23', '2005-5-15', '1.69', '760500', 'KTMT'),
('GV14', 'TRUONG MINH CHAU', 'THS', 'GV', 'NU', '1976-11-30', '2005-5-15', '3.00', '1350000', 'MTT'),
('GV15', 'LE HA THANH', 'THS', 'GV', 'NAM', '1976-5-4', '2005-5-15', '3.00', '1350000', 'KHMT');
ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA);
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_GIOITINHGV CHECK (GIOITINH IN ('NAM', 'NU'));
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_HOCVI CHECK (HOCVI IN ('CN', 'KS','THS', 'TS', 'PTS'));
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_TUOIVL CHECK (DATEDIFF(YEAR, NGSINH, NGVL) >= 22);


CREATE TABLE LOP
(
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4)
)
INSERT INTO LOP VALUES
('K11', 'LOP 1 KHOA 1', 'K1108', '11', 'GV07'),
('K12', 'LOP 2 KHOA 1', 'K1205', '12', 'GV09'),
('K13', 'LOP 3 KHOA 1', 'K1305', '12', 'GV14');
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN (MAGV);
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_HOCVIEN FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN (MAHV);


CREATE TABLE HOCVIEN
(
	MAHV CHAR(5) PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3)
)
INSERT INTO HOCVIEN VALUES 
('K1101', 'NGUYEN VAN', 'A', '1986-1-27', 'NAM', 'TPHCM', 'K11'),
('K1102', 'TRAN NGOC', 'HAN', '1986-3-14', 'NU', 'KIEN GIANG', 'K11'),
('K1103', 'HA DUY', 'LAP', '1986-4-18', 'NAM', 'NGHE AN', 'K11'),
('K1104', 'TRAN NGOC', 'LINH', '1986-3-30', 'NU', 'TAY NINH', 'K11'),
('K1105', 'TRAN MINH', 'LONG', '1986-2-27', 'NAM', 'TPHCM', 'K11'),
('K1106', 'LE NHAT', 'MINH', '1986-1-24', 'NAM', 'TPHCM', 'K11'),
('K1107', 'NGUYEN NHU', 'NHUT', '1986-1-27', 'NAM', 'HA NOI', 'K11'),
('K1108', 'NGUYEN MANH', 'TAM', '1986-2-27', 'NAM', 'KIEN GIANG', 'K11'),
('K1109', 'PHAN THI THANH', 'TAM', '1986-1-27', 'NU', 'VINH LONG', 'K11'),
('K1110', 'LE HOAI', 'THUONG', '1986-2-5', 'NU', 'CAN THO', 'K11'),
('K1111', 'LE HA', 'VINH', '1986-12-25', 'NAM', 'VINH LONG', 'K11'),
('K1201', 'NGUYEN VAN', 'B', '1986-2-11', 'NAM', 'TPHCM', 'K12'),
('K1202', 'NGUYEN THI KIM', 'DUYEN', '1986-1-18', 'NU', 'TPHCM', 'K12'),
('K1203', 'TRAN THI KIM', 'DUYEN', '1986-9-17', 'NU', 'TPHCM', 'K12'),
('K1204', 'TRUONG MY', 'HANH', '1986-5-19', 'NU', 'DONG NAI', 'K12'),
('K1205', 'NGUYEN THANH', 'NAM', '1986-4-17', 'NAM', 'TPHCM', 'K12'),
('K1206', 'NGUYEN THI TRUC', 'THANH',' 1986-3-4', 'NU', 'KIEN GIANG', 'K12'),
('K1207', 'TRAN THI BICH', 'THUY', '1986-2-8', 'NU', 'NGHE AN', 'K12'),
('K1208', 'HUYNH THI KIM', 'TRIEU', '1986-4-8', 'NU', 'TAY NINH', 'K12'),
('K1209', 'PHAM THANH', 'TRIEU', '1986-2-23', 'NAM', 'TPHCM', 'K12'),
('K1210', 'NGO THANH', 'TUAN', '1986-2-14', 'NAM', 'TPHCM', 'K12'),
('K1211', 'DO THI', 'XUAN', '1986-3-9', 'NU', 'HA NOI', 'K12'),
('K1212', 'LE THI PHI', 'YEN', '1986-3-12', 'NU', 'TPHCM', 'K12'),
('K1301', 'NGUYEN THI KIM', 'CUC', '1986-6-9', 'NU', 'KIEN GIANG', 'K13'),
('K1302', 'TRUONG THI MY', 'HIEN', '1986-3-18', 'NU', 'NGHE AN', 'K13'),
('K1303', 'LE DUC', 'HIEN', '1986-3-21', 'NAM', 'TAY NINH', 'K13'),
('K1304', 'LE QUANG', 'HIEN', '1986-4-18', 'NAM', 'TPHCM', 'K13'),
('K1305', 'LE THI', 'HUONG', '1986-3-27', 'NU', 'TPHCM', 'K13'),
('K1306', 'NGUYEN THAI', 'HUU', '1986-3-30', 'NAM', 'HA NOI', 'K13'),
('K1307', 'TRAN MINH', 'MAN', '1986-5-28', 'NAM', 'TPHCM', 'K13'),
('K1308', 'NGUYEN HIEU', 'NGHIA', '1986-4-8', 'NAM', 'KIEN GIANG', 'K13'),
('K1309', 'NGUYEN TRUNG', 'NGHIA', '1987-1-18', 'NAM', 'NGHE AN', 'K13'),
('K1310', 'TRAN THI HONG', 'THAM', '1986-4-22', 'NU', 'TAY NINH', 'K13'),
('K1311', 'TRAN MINH', 'THUC', '1986-4-4', 'NAM', 'TPHCM', 'K13'),
('K1312', 'NGUYEN THI KIM', 'YEN', '1986-9-7', 'NU', 'TPHCM', 'K13');

ALTER TABLE HOCVIEN ADD CONSTRAINT FK_HOCVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP);
ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(40), DIEMTB NUMERIC(4,2), XEPLOAI VARCHAR(10);
ALTER TABLE HOCVIEN ADD CONSTRAINT CK_MAHV CHECK (LEN(MAHV) = 5 AND SUBSTRING(MAHV, 1, 3) LIKE '[A-Z0-9][A-Z0-9][A-Z0-9]' AND SUBSTRING(MAHV, 4, 2) LIKE '[0-9][0-9]'); --SUBSTRING(EXP, START, LENGTH): CẮT CHỮ TỪ VỊ TRÍ START ĐẾN VỊ TRÍ CÁCH START 1 ĐOẠN LENGTH
ALTER TABLE HOCVIEN ADD CONSTRAINT CK_GIOITINHHV CHECK (GIOITINH IN ('NAM', 'NU'));
ALTER TABLE HOCVIEN ADD CONSTRAINT CK_TUOI CHECK (2006 - YEAR(NGSINH) >= 18);


CREATE TABLE GIANGDAY
(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH)
)
INSERT INTO GIANGDAY VALUES
('K11', 'THDC', 'GV07', '1', '2006', '2006-1-2', '2006-5-12'),
('K12', 'THDC', 'GV06', '1', '2006', '2006-1-2', '2006-5-12'),
('K13', 'THDC', 'GV15', '1', '2006', '2006-1-2', '2006-5-12'),
('K11', 'CTRR', 'GV02', '1', '2006', '2006-1-9', '2006-5-17'),
('K12', 'CTRR', 'GV02', '1', '2006', '2006-1-9', '2006-5-17'),
('K13', 'CTRR', 'GV08', '1', '2006', '2006-1-9', '2006-5-17'),
('K11', 'CSDL', 'GV05', '2', '2006', '2006-6-1', '2006-7-15'),
('K12', 'CSDL', 'GV09', '2', '2006', '2006-6-1', '2006-7-15'),
('K13', 'CTDLGT', 'GV15', '2', '2006', '2006-6-1', '2006-7-15'),
('K13', 'CSDL', 'GV05', '3', '2006', '2006-8-1', '2006-12-15'), 
('K13', 'DHMT', 'GV07', '3', '2006', '2006-8-1', '2006-12-15'), 
('K11', 'CTDLGT', 'GV15', '3', '2006', '2006-8-1', '2006-12-15'), 
('K12', 'CTDLGT', 'GV15', '3', '2006', '2006-8-1', '2006-12-15'), 
('K11', 'HDH', 'GV04', '1', '2007', '2007-1-2', '2007-2-18'),
('K12', 'HDH', 'GV04', '1', '2007', '2007-1-2', '2007-3-20'),
('K12', 'DHMT', 'GV07', '1', '2007', '2007-1-2', '2007-3-20');
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP);
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GIANGDAY_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH);
ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN (MAGV);
ALTER TABLE GIANGDAY ADD CONSTRAINT CK_HOCKY CHECK (HOCKY >= 1 AND HOCKY <= 3);
ALTER TABLE GIANGDAY ADD CONSTRAINT CK_NGAY CHECK (TUNGAY < DENNGAY);


CREATE TABLE KETQUATHI
(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	PRIMARY KEY (MAHV, MAMH, LANTHI)
)
INSERT INTO KETQUATHI VALUES
('K1101', 'CSDL', '1', '2006-7-20', '10.00', 'DAT'),
('K1101', 'CTDLGT', '1', '2006-12-28', '9.00', 'DAT'),
('K1101', 'THDC', '1', '2006-5-20', '9.00', 'DAT'),
('K1101', 'CTRR', '1', '2006-5-13', '9.50', 'DAT'),
('K1102', 'CSDL','1', '2006-7-20', '4.00', 'KHONG DAT'),
('K1102', 'CSDL','2', '2006-7-27', '4.25', 'KHONG DAT'),
('K1102', 'CSDL','3', '2006-8-10', '4.50', 'KHONG DAT'),
('K1102', 'CTDLGT','1', '2006-12-28', '4.50', 'KHONG DAT'),
('K1102', 'CTDLGT','2', '2007-1-5', '4.00', 'KHONG DAT'),
('K1102', 'CTDLGT','3', '2006-1-15', '6.00', 'DAT'),
('K1102', 'THDC','1', '2006-5-20', '5.00', 'DAT'),
('K1102', 'CTRR','1', '2006-5-13', '7.00', 'DAT'),
('K1103', 'CSDL', '1', '2006-7-20', '3.50', 'KHONG DAT'),
('K1103', 'CSDL', '2', '2006-7-27', '8.25', 'DAT'),
('K1103', 'CTDLGT', '1', '2006-12-28', '7.00', 'DAT'),
('K1103', 'THDC', '1', '2006-5-20', '8.00', 'DAT'),
('K1103', 'CTRR', '1', '2006-5-13', '6.50', 'DAT'),
('K1104', 'CSDL', '1', '2006-7-20', '3.75', 'KHONG DAT'),
('K1104', 'CTDLGT', '1', '2006-12-28', '4.00', 'KHONG DAT'),
('K1104', 'THDC', '1', '2006-5-20', '4.00', 'KHONG DAT'),
('K1104', 'CTRR', '1', '2006-5-13', '4.00', 'KHONG DAT'),
('K1104', 'CTRR', '2', '2006-5-20', '3.50', 'KHONG DAT'),
('K1104', 'CSDL', '3', '2006-6-30', '4.00', 'KHONG DAT'),
('K1201', 'CSDL', '1', '2006-7-20', '6.00', 'DAT'),
('K1201', 'CTDLGT', '1', '2006-12-28', '5.00', 'DAT'),
('K1201', 'THDC', '1', '2006-5-20', '8.50', 'DAT'),
('K1201', 'CTRR', '1', '2006-5-13', '9.00', 'DAT'),
('K1202', 'CSDL', '1', '2006-7-20', '8.00', 'DAT'),
('K1202', 'CTDLGT', '1', '2006-12-28', '4.00', 'KHONG DAT'),
('K1202', 'CTDLGT', '2', '2007-1-5', '5.00', 'DAT'),
('K1202', 'THDC', '1', '2006-5-20', '4.00', 'KHONG DAT'),
('K1202', 'THDC', '2', '2006-5-27', '8.00', 'KHONG DAT'),
('K1202', 'CTRR', '1', '2006-5-13', '3.00', 'KHONG DAT'),
('K1202', 'CTRR', '2', '2006-5-20', '4.00', 'KHONG DAT'),
('K1202', 'CTRR', '3', '2006-6-30', '6.25', 'KHONG DAT'),
('K1203', 'CSDL', '1', '2006-7-20', '9.25', 'DAT'),
('K1203', 'CTDLGT', '1', '2006-12-28', '9.50', 'DAT'),
('K1203', 'THDC', '1', '2006-5-20', '10.00', 'DAT'),
('K1203', 'CTRR', '1', '2006-5-13', '10.00', 'DAT'),
('K1204', 'CSDL', '1', '2006-7-20', '8.50', 'DAT'),
('K1204', 'CTDLGT', '1', '2006-12-28', '6.75', 'DAT'),
('K1204', 'THDC', '1', '2006-5-20', '4.00', 'KHONG DAT'),
('K1204', 'CTRR', '1', '2006-5-13', '6.00', 'DAT'),
('K1301', 'CSDL', '1', '2006-12-20', '4.25', 'KHONG DAT'),
('K1301', 'CTDLGT', '1', '2006-7-25', '8.00', 'DAT'),
('K1301', 'THDC', '1', '2006-5-20', '7.75', 'DAT'),
('K1301', 'CTRR', '1', '2006-5-13', '8.00', 'DAT'),
('K1302', 'CSDL', '1', '2006-12-20', '6.75', 'DAT'),
('K1302', 'CTDLGT', '1', '2006-7-25', '5.00', 'DAT'),
('K1302', 'THDC', '1', '2006-5-20', '8.00', 'DAT'),
('K1302', 'CTRR', '1', '2006-5-13', '8.50', 'DAT'),
('K1303', 'CSDL', '1', '2006-12-20', '4.00', 'KHONG DAT'),
('K1303', 'CTDLGT', '1', '2006-7-25', '4.50', 'KHONG DAT'),
('K1303', 'CTDLGT', '2', '2006-8-7', '4.00', 'KHONG DAT'),
('K1303', 'CTDLGT', '3', '2006-8-15', '4.25', 'KHONG DAT'),
('K1303', 'THDC', '1', '2006-5-20', '4.50', 'KHONG DAT'),
('K1303', 'CTRR', '1', '2006-5-13', '3.25', 'KHONG DAT'),
('K1303', 'CTRR', '2', '2006-5-20', '5.00', 'DAT'),
('K1304', 'CSDL', '1', '2006-12-20', '7.75', 'DAT'),
('K1304', 'CTDLGT', '1', '2006-7-25', '9.75', 'DAT'),
('K1304', 'THDC', '1', '2006-5-20', '5.50', 'DAT'),
('K1304', 'CTRR', '1', '2006-5-13', '5.00', 'DAT'),
('K1305', 'CSDL', '1', '2006-12-20', '9.25', 'DAT'),
('K1305', 'CTDLGT', '1', '2006-7-25', '10.00', 'DAT'),
('K1305', 'THDC', '1', '2006-5-20', '8.00', 'DAT'),
('K1305', 'CTRR', '1', '2006-5-13', '10.00', 'DAT');
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KETQUATHI_HOCVIEN FOREIGN KEY (MAHV) REFERENCES HOCVIEN (MAHV);
ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KETQUATHI_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH);
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_DIEM CHECK (DIEM >= 0 AND DIEM <= 10);
UPDATE KETQUATHI
SET KQUA =
	CASE 
		WHEN DIEM >= 5 AND DIEM <= 10 THEN 'DAT'
		ELSE 'KHONG DAT'
	END;
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_LANTHI CHECK (LANTHI <= 3 AND LANTHI >= 0);


--1
SELECT HV.MAHV, HV.HO, HV.TEN, HV.NGSINH, L.MALOP
FROM HOCVIEN HV INNER JOIN LOP L ON HV.MAHV = L.TRGLOP;

--2
SELECT HV.MAHV, HV.HO, HV.TEN, KQT.LANTHI, KQT.DIEM
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MALOP = 'K12' AND KQT.MAMH = 'CTRR';

--3
SELECT HV.MAHV, HV.HO, HV.TEN, KQT.MAMH
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.LANTHI = '1' AND KQT.KQUA = 'DAT';

--4 
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MALOP = 'K11' AND KQT.MAMH = 'CTRR' AND KQT.LANTHI = '1' AND KQT.KQUA = 'KHONG DAT';

--5 
SELECT DISTINCT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MALOP LIKE 'K%' AND KQT.MAMH = 'CTRR' AND KQT.KQUA = 'KHONG DAT';

--II
--1
UPDATE GIAOVIEN 
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA 
				FROM KHOA);

--2 
UPDATE HOCVIEN 
SET DIEMTB = (SELECT AVG(KQT.DIEM)
				FROM KETQUATHI KQT
				WHERE MAHV = KQT.MAHV
				GROUP BY KQT.MAHV, KQT.MAMH
				HAVING KQT.LANTHI = (SELECT MAX(LANTHI)
									FROM KETQUATHI 
									WHERE MAHV = KQT.MAHV));

--3
UPDATE HOCVIEN 
SET GHICHU = 'Cam thi'
WHERE MAHV = (SELECT KQT.MAHV
			FROM KETQUATHI KQT
			WHERE MAHV = KQT.MAHV
			AND KQT.LANTHI = '3' AND KQT.DIEM < '5');

--4
UPDATE HOCVIEN 
SET XEPLOAI = 
	CASE 
		WHEN DIEMTB >= '9' THEN 'XS'
		WHEN DIEMTB >= '8' AND DIEMTB < '9' THEN 'G'
		WHEN DIEMTB >= '6.5' AND DIEMTB < '8' THEN 'K'
		WHEN DIEMTB >= '5' AND DIEMTB < '6.5' THEN 'TB'
		ELSE 'Y'
	END;

--III
--6
SELECT MH.TENMH
FROM MONHOC MH INNER JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
				INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE GV.HOTEN = 'TRAN TAM THANH' AND GD.HOCKY = '1' AND GD.NAM = '2006';

--7
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH INNER JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
				INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE GD.HOCKY = '1' AND GD.NAM = '2006' AND GV.MAGV = (SELECT MAGVCN
														FROM LOP 
														WHERE GV.MAGV = MAGVCN AND MALOP = 'K11');

--8
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN LOP L ON HV.MAHV = L.TRGLOP
				INNER JOIN GIANGDAY GD ON L.MALOP = GD.MALOP
				INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
				INNER JOIN MONHOC MH ON GD.MAMH = MH.MAMH
WHERE GV.HOTEN = 'NGUYEN TO LAN' AND MH.TENMH = 'CO SO DU LIEU' AND HV.MAHV IN (SELECT TRGLOP
																				FROM LOP
																				WHERE HV.MAHV = TRGLOP);

--9
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH_TRUOC
WHERE DK.MAMH = (SELECT MAMH
				FROM MONHOC
				WHERE TENMH = 'CO SO DU LIEU');

--10
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH
WHERE DK.MAMH_TRUOC = (SELECT MAMH
						FROM MONHOC
						WHERE TENMH = 'CAU TRUC ROI RAC');

--11
SELECT GV.HOTEN
FROM GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAMH = 'CTRR' AND GD.MALOP = 'K11' AND GD.HOCKY = '1' AND GD.NAM = '2006'
INTERSECT 
SELECT GV.HOTEN
FROM GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAMH = 'CTRR' AND GD.MALOP = 'K12' AND GD.HOCKY = '1' AND GD.NAM = '2006';

--12
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.MAMH = 'CSDL' AND KQT.LANTHI = '1' AND KQT.KQUA = 'KHONG DAT'
EXCEPT
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.MAMH = 'CSDL' AND KQT.LANTHI = '2';

--13
SELECT MAGV, HOTEN
FROM GIAOVIEN  
WHERE MAGV <> ALL (SELECT MAGV 
					FROM GIANGDAY);

--14
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV <> ALL (SELECT GD.MAGV 
					FROM GIANGDAY GD INNER JOIN MONHOC MH ON GD.MAMH = MH.MAMH
									INNER JOIN KHOA K ON MH.MAKHOA = K.MAKHOA
					WHERE GV.MAKHOA = K.MAKHOA);

--15
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MALOP = 'K11' AND KQT.LANTHI > '3' AND KQT.KQUA = 'KHONG DAT'
UNION 
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MALOP = 'K11' AND KQT.LANTHI = '2' AND KQT.MAMH = 'CTRR' AND KQT.DIEM = '5';

--16
SELECT GV.HOTEN
FROM GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAMH = 'CTRR'
GROUP BY GV.HOTEN, GD.MAGV, GD.HOCKY, GD.NAM
HAVING COUNT(DISTINCT GD.MALOP) >= '2';


--17
SELECT HV.MAHV, HV.HO, HV.TEN, KQT.DIEM
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.MAMH = 'CSDL' AND KQT.LANTHI = (SELECT MAX(LANTHI)
											FROM KETQUATHI
											WHERE MAMH = 'CSDL' AND MAHV = KQT.MAHV);

--18
SELECT HV.MAHV, HV.HO, HV.TEN, MAX(KQT.DIEM) AS DIEM_CAO_NHAT
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
				INNER JOIN MONHOC MH ON KQT.MAMH = MH.MAMH
WHERE MH.TENMH = 'CO SO DU LIEU'
GROUP BY HV.MAHV, HV.HO, HV.TEN;

--19
--1 KHOA
SELECT TOP 1 *
FROM KHOA
ORDER BY NGTLAP ASC;

--CAC KHOA THANH LAP CUNG NGAY SOM NHAT
SELECT *
FROM KHOA
WHERE NGTLAP = (SELECT MIN(NGTLAP)
				FROM KHOA);

--20
SELECT COUNT(MAGV) AS SL_GV
FROM GIAOVIEN
WHERE HOCHAM = 'GS' OR HOCHAM = 'PGS';

--21
SELECT K.MAKHOA, K.TENKHOA, GV.HOCVI, COUNT(*) AS SL_GV
FROM GIAOVIEN GV INNER JOIN KHOA K ON GV.MAKHOA = K.MAKHOA
WHERE GV.HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS') 
GROUP BY K.MAKHOA, K.TENKHOA, GV.HOCVI
ORDER BY K.MAKHOA, GV.HOCVI;

--22
SELECT MH.MAMH, MH.TENMH, KQT.KQUA, COUNT(DISTINCT KQT.MAHV) AS SL_HV
FROM MONHOC MH INNER JOIN KETQUATHI KQT ON MH.MAMH = KQT.MAMH
GROUP BY MH.MAMH, MH.TENMH, KQT.KQUA
ORDER BY MH.MAMH, KQT.KQUA;

--23
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV INNER JOIN GIANGDAY GD  ON GV.MAGV = GD.MAGV
				INNER JOIN LOP L ON GD.MALOP = L.MALOP
WHERE GV.MAGV = L.MAGVCN
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(GD.MAMH) >= 1;

--24
SELECT TOP 1 HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN LOP L ON HV.MAHV = L.TRGLOP
ORDER BY L.SISO;

--25
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN LOP L ON HV.MAHV = L.TRGLOP
				INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.KQUA = 'KHONG DAT'
GROUP BY HV.HO, HV.TEN
HAVING COUNT(DISTINCT KQT.MAMH) > 3;

--26
SELECT TOP 1 HV.HO, HV.TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.DIEM IN ('9', '10')
GROUP BY HV.HO, HV.TEN
ORDER BY COUNT(DISTINCT KQT.MAMH) DESC;

--27
SELECT L.MALOP, HV.MAHV, HV.HO, HV.TEN, COUNT(DISTINCT KQT.MAMH) AS SL_MH
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
				INNER JOIN LOP L ON HV.MALOP = L.MALOP
WHERE KQT.DIEM IN ('9', '10') 
GROUP BY L.MALOP, HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(DISTINCT KQT.MAMH) = (
    SELECT MAX(NumSubjectsWithHighScores)
    FROM (
        SELECT COUNT(DISTINCT KQT2.MAMH) AS NumSubjectsWithHighScores
        FROM KETQUATHI KQT2
        INNER JOIN HOCVIEN HV2 ON KQT2.MAHV = HV2.MAHV
        WHERE KQT2.DIEM IN ('9', '10') AND HV2.MALOP = L.MALOP
        GROUP BY KQT2.MAHV
    ) AS Subquery
)
ORDER BY L.MALOP;

--28
SELECT HOCKY, NAM, MAGV, COUNT(MAMH) AS SO_MONHOC, COUNT(MALOP) AS SO_LOP
FROM GIANGDAY
GROUP BY HOCKY, NAM, MAGV
ORDER BY HOCKY, NAM ASC;

--29
SELECT 
    GD.MAGV, 
    GV.HOTEN, 
    GD.HOCKY, 
    GD.NAM,
    COUNT(*) AS SoLanGiangDay
FROM 
    GIANGDAY GD
JOIN 
    GIAOVIEN GV ON GD.MAGV = GV.MAGV
GROUP BY 
    GD.MAGV, 
    GV.HOTEN, 
    GD.HOCKY, 
    GD.NAM
HAVING 
    COUNT(*) = (
        SELECT MAX(SoLanGiangDay)
        FROM (
            SELECT 
                GD1.MAGV, 
                COUNT(*) AS SoLanGiangDay
            FROM 
                GIANGDAY GD1
            WHERE 
                GD1.HOCKY = GD.HOCKY AND GD1.NAM = GD.NAM
            GROUP BY 
                GD1.MAGV
        ) AS Subquery
    )
ORDER BY 
    GD.NAM, 
    GD.HOCKY;

--30
SELECT
	TOP 1 
	MH.MAMH,
	MH.TENMH,
	COUNT(KQT.MAHV) AS SL_SV
FROM 
	KETQUATHI KQT
INNER JOIN
	MONHOC MH ON KQT.MAMH = MH.MAMH
WHERE 
	KQT.LANTHI = '1' AND KQT.KQUA = 'KHONG DAT'
GROUP BY
	MH.MAMH,
	MH.TENMH;

--31
SELECT 
    HV.MAHV, 
    HV.HO,
	HV.TEN
FROM 
    HOCVIEN HV
JOIN 
    KETQUATHI T ON HV.MAHV = T.MAHV
WHERE 
    T.LANTHI = 1 AND T.KQUA = 'DAT'
GROUP BY 
    HV.MAHV, HV.HO, HV.TEN
HAVING 
    COUNT(DISTINCT T.MAMH) = (
        SELECT COUNT(DISTINCT MAMH) 
        FROM KETQUATHI 
        WHERE MAHV = HV.MAHV AND LANTHI = 1 
    );

--32 
SELECT 
	HV.MAHV,
	HV.HO,
	HV.TEN
FROM
	HOCVIEN HV
INNER jOIN
	KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE 
	KQT.KQUA = 'DAT' AND KQT.LANTHI = (SELECT MAX(LANTHI)
										FROM KETQUATHI 
										WHERE MAHV = HV.MAHV)
GROUP BY
	HV.MAHV, HV.HO, HV.TEN
HAVING 
	COUNT(DISTINCT KQT.MAMH) = (
		SELECT COUNT(DISTINCT MAMH)
		FROM KETQUATHI
		WHERE MAHV = HV.MAHV AND LANTHI = (SELECT MAX(KQT2.LANTHI)
											FROM KETQUATHI KQT2
											WHERE KQT2.MAHV = HV.MAHV)
		);

--33
SELECT 
    HV.MAHV, 
    HV.HO,
	HV.TEN
FROM 
    HOCVIEN HV
JOIN 
    KETQUATHI T ON HV.MAHV = T.MAHV
WHERE 
    T.LANTHI = 1 AND T.KQUA = 'DAT'
GROUP BY 
    HV.MAHV, HV.HO, HV.TEN
HAVING 
    COUNT(DISTINCT T.MAMH) = (
        SELECT COUNT(MAMH) 
        FROM MONHOC
    );

--34
SELECT 
	HV.MAHV,
	HV.HO,
	HV.TEN
FROM
	HOCVIEN HV
INNER jOIN
	KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE 
	KQT.KQUA = 'DAT' AND KQT.LANTHI = (SELECT MAX(LANTHI)
										FROM KETQUATHI 
										WHERE MAHV = HV.MAHV)
GROUP BY
	HV.MAHV, HV.HO, HV.TEN
HAVING 
	COUNT(DISTINCT KQT.MAMH) = (
		SELECT COUNT(MAMH)
		FROM MONHOC
		);

--35
SELECT 
    T.MAMH,
    T.MAHV,
    HV.HO,
	HV.TEN,
    T.DIEM
FROM 
    KETQUATHI T
JOIN 
    HOCVIEN HV ON T.MAHV = HV.MAHV
WHERE 
    T.LANTHI = (  -- Chỉ xét lần thi sau cùng
        SELECT MAX(LANTHI)
        FROM KETQUATHI
        WHERE MAMH = T.MAMH AND MAHV = T.MAHV
    )
AND 
    T.DIEM = (  -- Lọc ra học viên có điểm cao nhất trong mỗi môn
        SELECT MAX(DIEM)
        FROM KETQUATHI
        WHERE MAMH = T.MAMH
        AND LANTHI = (  -- Chỉ xét lần thi cuối cùng
            SELECT MAX(LANTHI)
            FROM KETQUATHI
            WHERE MAMH = T.MAMH AND MAHV = T.MAHV
        )
    )
AND
    NOT EXISTS (  -- Đảm bảo chỉ có một học viên có điểm cao nhất trong môn học
        SELECT 1
        FROM KETQUATHI T2
        WHERE T2.MAMH = T.MAMH
        AND T2.DIEM > T.DIEM  -- Kiểm tra xem có học viên khác có điểm cao hơn không
    )
ORDER BY 
    T.MAMH;
	
--I
--9
CREATE TRIGGER TG_TRGLOP
ON LOP
FOR INSERT, UPDATE
AS
    IF EXISTS (
        SELECT 1
        FROM INSERTED I 
        LEFT JOIN HOCVIEN H ON I.TRGLOP = H.MAHV AND I.MALOP = H.MALOP
        WHERE H.MAHV IS NULL
    )
    BEGIN
        PRINT 'LOP TRUONG PHAI LA HOC VIEN CUA LOP NAY';
        ROLLBACK TRANSACTION
    END;

--10
CREATE TRIGGER TG_TRGKHOA
ON KHOA
FOR INSERT, UPDATE
AS
	IF EXISTS (
		SELECT 1
		FROM INSERTED I 
		LEFT JOIN GIAOVIEN GV ON I.TRGKHOA = GV.MAGV AND I.MAKHOA = GV.MAKHOA
		WHERE GV.MAGV IS NULL OR HOCVI NOT IN ('TS', 'PTS')
		)
	BEGIN 
		PRINT 'TRUONG KHOA PHAI LA GIAO VIEN CUA KHOA NAY VA CO HOC VI "TS" HOAC "PTS"'
		ROLLBACK TRAN
	END;

--15
CREATE TRIGGER TG_TGTHI
ON KETQUATHI
FOR INSERT, UPDATE 
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN GIANGDAY GD ON I.MAMH = GD.MAMH 
						JOIN HOCVIEN HV ON I.MAHV = HV.MAHV
		WHERE DENNGAY <= NGTHI
		)
	BEGIN 
		PRINT 'HOC VIEN CHI DUOC THI KHI LOP DA HOC XONG MON NAY'
		ROLLBACK TRAN
	END;

--16
CREATE TRIGGER TG_SOMONHOC
ON GIANGDAY
FOR INSERT, UPDATE
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN LOP L ON I.MALOP = L.MALOP
		GROUP BY L.MALOP
		HAVING COUNT(MAMH) > 3
		)
	BEGIN 
		PRINT '1 LOP CHI DUOC HOC TOI DA 3 MON' 
		ROLLBACK TRAN
	END;

--17
CREATE TRIGGER TG_SISO
ON LOP 
FOR INSERT, UPDATE
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN HOCVIEN HV ON I.MALOP = HV.MALOP
		GROUP BY I.MALOP, SISO
		HAVING COUNT(MAHV) <> SISO
		)
	BEGIN 
		PRINT 'SI SO PHAI BANG SO HOC VIEN THUOC LOP NAY'
		ROLLBACK TRAN
	END;

--18
CREATE TRIGGER TG_DIEUKIEN
ON DIEUKIEN 
FOR INSERT, UPDATE
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I 
		WHERE MAMH = MAMH_TRUOC 
		)
	BEGIN
        PRINT 'Khong duoc phep co cap gia tri ("MAMH", "MAMH_TRUOC") giong nhau!';
        ROLLBACK TRANSACTION;
        RETURN;
    END

    IF EXISTS (
        SELECT 1
        FROM INSERTED I JOIN DIEUKIEN D ON (I.MAMH = D.MAMH_TRUOC AND I.MAMH_TRUOC = D.MAMH)
    )
    BEGIN
        PRINT 'Khong duoc phep co cap doi xung ("MAMH", "MAMH_TRUOC") va ("MAMH_TRUOC", "MAMH")!';
        ROLLBACK TRANSACTION;
        RETURN;
    END;

--19
CREATE TRIGGER TG_MUCLUONG
ON GIAOVIEN
FOR INSERT, UPDATE
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN GIAOVIEN GV ON (I.HOCHAM = GV.HOCHAM 
											AND I.HOCVI = GV.HOCVI
											AND I.HESO = GV.HESO)
		WHERE I.MUCLUONG <> GV.MUCLUONG
		)
	BEGIN 
		PRINT 'CAC GIAO VIEN CO CUNG HOC VI, HOC HAM, HE SO LUONG THI MUC LUONG BANG NHAU!'
		ROLLBACK TRAN
	END;

--20
CREATE TRIGGER TG_LANTHI
ON KETQUATHI 
FOR INSERT, UPDATE
AS
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN KETQUATHI KQT ON (I.MAHV = KQT.MAHV AND I.LANTHI - 1 = KQT.LANTHI AND I.MAMH = KQT.MAMH)
		WHERE KQT.KQUA >= 5 
		)
	BEGIN 
		PRINT 'HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC < 5'
		ROLLBACK TRAN
	END;

--21
CREATE TRIGGER TG_NGTHI_LANTHISAU
ON KETQUATHI 
FOR INSERT, UPDATE
AS
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN KETQUATHI KQT ON (I.MAHV = KQT.MAHV AND I.LANTHI - 1 = KQT.LANTHI AND I.MAMH = KQT.MAMH)
		WHERE I.NGTHI <= KQT.NGTHI
		)
	BEGIN 
		PRINT 'NGAY THI CUA LAN THI SAU PHAI LON HON NGAY THI CUA LAN THI TRUOC'
		ROLLBACK TRAN
	END;

--22
CREATE TRIGGER TG_TGTHI
ON KETQUATHI
FOR INSERT, UPDATE 
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN GIANGDAY GD ON I.MAMH = GD.MAMH 
						JOIN HOCVIEN HV ON I.MAHV = HV.MAHV
		WHERE DENNGAY <= NGTHI
		)
	BEGIN 
		PRINT 'HOC VIEN CHI DUOC THI KHI LOP DA HOC XONG MON NAY'
		ROLLBACK TRAN
	END;

--23
CREATE TRIGGER TG_GIANGDAYTRUOC_SAU
ON GIANGDAY
FOR INSERT, UPDATE
AS
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN DIEUKIEN DK ON I.MAMH = DK.MAMH
		WHERE MAMH_TRUOC IS NOT NULL AND TUNGAY <= (SELECT DENNGAY
													FROM GIANGDAY GD JOIN DIEUKIEN DK1 ON GD.MAMH = DK1.MAMH_TRUOC
													WHERE I.MALOP = GD.MALOP)
		)
	BEGIN 
		PRINT 'PHAI DAY THEO THU TU MON HOC'
		ROLLBACK TRAN
	END;

--24 
CREATE TRIGGER TG_GIAOVIEN_MONHOC_KHOA
ON GIANGDAY
FOR INSERT, UPDATE 
AS 
	IF EXISTS (
		SELECT 1
		FROM INSERTED I JOIN MONHOC MH ON I.MAMH = MH.MAMH
						JOIN GIAOVIEN GV ON I.MAGV = GV.MAGV
		WHERE GV.MAKHOA <> MH.MAKHOA
		)
	BEGIN 
		PRINT 'GIAO VIEN CHI DUOC PHAN CONG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH'
		ROLLBACK TRAN
	END;

