CREATE DATABASE BAITHI
USE BAITHI

CREATE TABLE SACH (
    MASACH VARCHAR(20) PRIMARY KEY,  -- Mã sách duy nhất
    TENSACH VARCHAR(255) NOT NULL,   -- Tên sách
    THELOAI VARCHAR(100),            -- Thể loại sách
    TACGIA VARCHAR(255),             -- Tác giả sách
    NGXB DATE,                       -- Ngày xuất bản
    NHAXB VARCHAR(255)               -- Đơn vị xuất bản
);

CREATE TABLE DVTOCHUC (
    MADV VARCHAR(20) PRIMARY KEY,     -- Mã đơn vị tổ chức duy nhất
    TENDV VARCHAR(255) NOT NULL,      -- Tên đơn vị tổ chức
    TENNGDD VARCHAR(255),             -- Tên người đại diện đơn vị
    NGTL DATE                         -- Ngày thành lập
);

CREATE TABLE SUKIEN(
	MASK VARCHAR(20) PRIMARY KEY,
	MASACH VARCHAR(20),
	MADV VARCHAR(20),
	TGBD DATETIME,
	TGKT DATETIME,
	DIADIEM VARCHAR(100),
	SLDK INT,
	FOREIGN KEY (MASACH) REFERENCES SACH(MASACH) ON DELETE CASCADE,
	FOREIGN KEY (MADV) REFERENCES DVTOCHUC(MADV) ON DELETE CASCADE
);

CREATE TABLE NGTHAMGIA(
	MANTG VARCHAR(20) PRIMARY KEY,
	TENNTG VARCHAR(50) NOT NULL,
	GIOITINH VARCHAR(5),
	NGSINH DATE,
	NGHENGHIEP VARCHAR(20)
);

CREATE TABLE THAMGIA(
	MANTG VARCHAR(20),
	MASK VARCHAR(20),
	VAITRO VARCHAR(50),
	PRIMARY KEY(MANTG, MASK),
	FOREIGN KEY (MANTG) REFERENCES NGTHAMGIA(MANTG) ON DELETE CASCADE,
	FOREIGN KEY (MASK) REFERENCES SUKIEN(MASK) ON DELETE CASCADE
);

CREATE TABLE DANHGIA(
	MADG VARCHAR(20) PRIMARY KEY,
	MANTG VARCHAR(20),
	MASK VARCHAR(20),
	TGDG DATETIME,
	DIEMSO INT,
	NHANXET VARCHAR(20),
	FOREIGN KEY (MANTG) REFERENCES NGTHAMGIA(MANTG) ON DELETE CASCADE,
	FOREIGN KEY (MASK) REFERENCES SUKIEN(MASK) ON DELETE CASCADE
);

INSERT INTO SACH (MASACH, TENSACH, THELOAI, TACGIA, NGXB, NHAXB)
VALUES
('S001', 'Dat Viet yeu men', 'Van hoa', 'Pham Cong Son', '2022-03-12', 'Phuong Dong'),
('S002', 'Ly luan day hoc Ngu Van', 'Giao duc', 'Lan Tran Son', '2023-05-06', 'Dai hoc Quoc gia TP.HCM'),
('S003', 'Lung nguoi tham tham', 'Truyen ngan', 'Vu Thi Huyen Trang', '2024-03-12', 'Tre');

INSERT INTO DVTOCHUC (MADV, TENDV, TENNGDD, NGTL)
VALUES
('DV001', 'RI Event', 'Nguyen Cong Ninh', '2013-08-09'),('DV002', 'Mediapro', 'Huynh Long An', '2004-12-12'),('DV003', 'Hoang sa Viet', 'Nguyen Ngoc Lan', '2017-04-16');INSERT INTO SUKIEN (MASK, MASACH, MADV, TGBD, TGKT, DIADIEM, SLDK)VALUES('SK001', 'S001', 'DV003', '2023-04-16 09:00:00', '2023-04-16 11:00:00', 'Dai hoc su pham TP.HCM', '150'), ('SK002', 'S001', 'DV003', '2023-05-16 09:00:00', '2023-05-16 11:00:00', 'Nguyen Van Binh, Ben nghe, Quan 1', '200'),('SK003', 'S002', 'DV001', '2024-05-17 08:30:00', '2024-05-17 10:00:00', 'Dai hoc Bach Khoa TP.HCM', '100');INSERT INTO NGTHAMGIA (MANTG, TENNTG, GIOITINH, NGSINH, NGHENGHIEP)VALUES('N001', 'Huynh Long Nhat', 'Nam', '1999-08-15', 'Giao vien'),('N002', 'Nguyen Yen Nhi', 'Nu', '2003-04-16', 'Sinh vien'),('N003', 'Mai Thi Yen', 'Nu', '2010-05-17', 'Hoc sinh');CREATE TRIGGER TG_SK_INSERTON SUKIEN AFTER INSERT, UPDATEAS	IF EXISTS (		SELECT 1		FROM INSERTED 		WHERE DIADIEM LIKE 'Dai hoc%' AND DIADIEM LIKE '%TP.HCM' AND SLDK > 300)	BEGIN 		PRINT 'SO LUONG DU KIEN VUOT QUA 300'		ROLLBACK TRANSACTION	END;CREATE TRIGGER TG_DANHGIA_INSERTON DANHGIA AFTER INSERT, UPDATE AS	IF EXISTS (		SELECT 1		FROM INSERTED I JOIN THAMGIA TG ON I.MANTG = TG.MANTG		WHERE TG.VAITRO <> 'Khach tham gia')	BEGIN		PRINT 'KHONG DUOC DANH GIA'		ROLLBACK TRANSACTION	END;--5 SELECT NTG.MANTG, TENNTG, NGSINHFROM NGTHAMGIA NTG JOIN THAMGIA TG ON NTG.MANTG = TG.MANTG					JOIN SUKIEN SK ON TG.MASK = SK.MASK					JOIN SACH S ON SK.MASACH = S.MASACHWHERE TACGIA = 'Pham Cong Son' AND MONTH(TGBD) = 1 AND YEAR(TGBD) = 2023 ORDER BY NGSINH DESC;--6SELECT NTG.MANTG, TENNTGFROM NGTHAMGIA NTG JOIN DANHGIA DG ON NTG.MANTG = DG.MANTG					JOIN SUKIEN SK ON DG.MASK = SK.MASK					JOIN DVTOCHUC DV ON SK.MADV = DV.MADVWHERE TENDV = 'Mediapro'								EXCEPTSELECT NTG.MANTG, TENNTGFROM NGTHAMGIA NTG JOIN DANHGIA DG ON NTG.MANTG = DG.MANTG					JOIN SUKIEN SK ON DG.MASK = SK.MASK					JOIN DVTOCHUC DV ON SK.MADV = DV.MADVWHERE TENDV = 'Mediapro' AND DIEMSO > 2;--7SELECT SK.MASK, DV.MADV, COUNT(DISTINCT MANTG) AS SO_NGUOI_THAMGIA_DANHGIAFROM SUKIEN SK JOIN DANHGIA DG ON SK.MASK = DG.MASK				JOIN DVTOCHUC DV ON SK.MADV = DV.MADVWHERE DIEMSO = 5GROUP BY SK.MASK, DV.MADVORDER BY SK.MASK, DV.MADV;--8SELECT SK.MASK, DIADIEM, DV.MADV, COUNT(MADG) AS SO_LUOT_DANH_GIA_5FROM SUKIEN SK JOIN DVTOCHUC DV ON SK.MADV = DV.MADV				JOIN DANHGIA DG ON SK.MASK = DG.MASKGROUP BY SK.MASK, DIADIEM, DV.MADVHAVING COUNT(MADG) >= ALL (	SELECT COUNT(MADG)	FROM DANHGIA	WHERE DIEMSO = 5 	GROUP BY DV.MADV);--9SELECT NTG.MANTG, TENNTG, SK.MASKFROM NGTHAMGIA NTG JOIN DANHGIA DG ON NTG.MANTG = DG.MANTG					JOIN SUKIEN SK ON DG.MASK = SK.MASK					JOIN SACH S ON SK.MASACH = S.MASACHWHERE TACGIA = 'Lam Tran Son' AND NOT EXISTS (	SELECT 1 	FROM DANHGIA 	WHERE DIEMSO < 4 AND NTG.MANTG = MANTG)GROUP BY NTG.MANTG, TENNTG, SK.MASKHAVING COUNT(DG.MASK) = (	SELECT COUNT(MASK)	FROM SUKIEN SK1 JOIN SACH S1 ON SK1.MASACH = S1.MASACH	WHERE TACGIA = 'Lam Tran Son');
